### ISSUE TITLE
Adding text diff hash

### ISSUE THREAD

**Issue by mayaad** [edgi-govdata-archiving/versionista-outputter#10]
Would it be possible to add a column to the output spreadsheets that is a hash of the text diff (rather than the code diff hash)? This came up in the most recent analyst standing meeting. 

This would enable people to recognize things like the January 19 EPA snapshot, which is the same added text each time, but the underlying code is slightly different each time (has a date and time snapshot), meaning that it's not marked as a repeated change by the source diff hash.

**Comment by KrishnaKulkarni** [comment]
@mayaad Is this still important? I can work on this over the next 3 days if it is

**Comment by mayaad** [comment]
@KrishnaKulkarni yes, this would be great! i think the team would really appreciate this, and it would definitely help cut down on workflow time.

**Comment by mayaad** [comment]
@KrishnaKulkarni : ran into this issue twice last night. doesn't appear to be related to the run time or a particular page. also, this isn't the same type of error caused by timing out. 

`/Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/browser.rb:376:in command: There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it.  (Capybara::Poltergeist::BrowserError)`

`Poltergeist.BrowserError: TypeError: undefined is not an object (evaluating 'element.parentNode')
phantomjs://code/agent.js:165:30
isObsolete@phantomjs://code/agent.js:176:20
nodeCall@phantomjs://code/agent.js:85:24
externalCall@phantomjs://code/agent.js:13:32`



`global code`
`evaluateJavaScript@[native code]`
`evaluate@phantomjs://platform/webpage.js:390:39`
`evaluate@phantomjs://code/web_page.js:519:52`
`runCommand@phantomjs://code/web_page.js:549:27`
`phantomjs://code/browser.js:47:29`
`phantomjs://code/browser.js:22:32`
`visible@phantomjs://code/browser.js:241:78`
`runCommand@phantomjs://code/browser.js:89:36`
`run@phantomjs://code/cmd.js:35:37`
`runCommand@phantomjs://code/connection.js:17:81`
`commandReceived@phantomjs://code/connection.js:16:33`
`phantomjs://code/connection.js:1:64`

	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/browser.rb:112:in `visible?'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/node.rb:17:in `command'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/node.rb:115:in `visible?'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/element.rb:269:in `block in visible?'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/base.rb:81:in `synchronize'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/element.rb:269:in `visible?'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/queries/selector_query.rb:78:in `matches_filters?'`
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/result.rb:29:in `block in initialize'`
	from capybara_script.rb:1:in `each'
	from capybara_script.rb:1:in `each'
	from capybara_script.rb:1:in `each'
	from capybara_script.rb:1:in `each'`

**Comment by KrishnaKulkarni** [comment]
@mayaad Can you show me the about 50 lines of terminal output preceding this error?

**Comment by mayaad** [comment]
sorry, i don't have that terminal window open anymore. 

it just completed successfully for an hour pull. the output looks great! the identical text changes are being picked up even if the code diff isn't the same- this will be a huge help! 

let me try will the full time again and i'll see if i can get the error again. will post with 50 lines ahead too if that works.

**Comment by mayaad** [comment]
@KrishnaKulkarni : here's the latest update. i ran the script for one of the versionista accounts with no issues for the full 96 hour pull (and the text diff hash is amazing! i checked one of the sheets and between the code and text diffs, i only had to check ~25 of 140 changes!). 

then i ran it for the other account and got the same error as previously. i've pasted a longer chunk below, and i've saved the full terminal output (see attachment). 

[Terminal Saved Output.txt](https://github.com/edgi-govdata-archiving/versionista-outputter/files/880942/Terminal.Saved.Output.txt)



Visiting the comparison url: https://versionista.com/72897/6133986/10616189:0/
-- Successful visit!
Visiting https://versionista.com/72897/6133873/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6133873/10615853:0/
-- Successful visit!
Visiting https://versionista.com/72897/6129863/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6129863/10613334:0/
-- Successful visit!
Visiting https://versionista.com/72897/6129491/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6129491/10610195:0/
-- Successful visit!
Visiting https://versionista.com/72897/6148595/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6148595/10600408:0/
-- Successful visit!
Visiting https://versionista.com/72897/6148627/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6148627/10600337:0/
-- Successful visit!
Visiting https://versionista.com/72897/6162423/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6162423/10598897:0/
-- Successful visit!
Visiting https://versionista.com/72897/6133856/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6133856/10598845:0/
-- Successful visit!
Visiting https://versionista.com/72897/6148637/
-- Successful visit!
Visiting the comparison url: https://versionista.com/72897/6148637/10598727:0/
-- Successful visit!
/Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/browser.rb:376:in `command': There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it.  (Capybara::Poltergeist::BrowserError)

Poltergeist.BrowserError: TypeError: undefined is not an object (evaluating 'element.parentNode')
phantomjs://code/agent.js:165:30
isObsolete@phantomjs://code/agent.js:176:20
nodeCall@phantomjs://code/agent.js:85:24
externalCall@phantomjs://code/agent.js:13:32



global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
evaluate@phantomjs://code/web_page.js:519:52
runCommand@phantomjs://code/web_page.js:549:27
phantomjs://code/browser.js:47:29
phantomjs://code/browser.js:22:32
tag_name@phantomjs://code/browser.js:237:76
runCommand@phantomjs://code/browser.js:89:36
run@phantomjs://code/cmd.js:35:37
runCommand@phantomjs://code/connection.js:17:81
commandReceived@phantomjs://code/connection.js:16:33
phantomjs://code/connection.js:1:64
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/browser.rb:108:in `tag_name'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/node.rb:17:in `command'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/node.rb:111:in `tag_name'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/poltergeist-1.13.0/lib/capybara/poltergeist/node.rb:60:in `[]'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/element.rb:78:in `block in []'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/base.rb:85:in `synchronize'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/node/element.rb:78:in `[]'
	from capybara_script.rb:251:in `block in versionista_diff'
	from /Users/mayaanjurdietrich/.rvm/gems/ruby-2.2.3/gems/capybara-2.12.0/lib/capybara/session.rb:409:in `within_frame'
	from capybara_script.rb:249:in `versionista_diff'
	from capybara_script.rb:239:in `text_changes_only_diff'
	from capybara_script.rb:222:in `comparison_diff'
	from capybara_script.rb:171:in `block in scrape_archived_page_data'
	from capybara_script.rb:162:in `map'
	from capybara_script.rb:162:in `scrape_archived_page_data'
	from capybara_script.rb:74:in `block in scrape_each_page_version'
	from capybara_script.rb:72:in `map'
	from capybara_script.rb:72:in `scrape_each_page_version'
	from capybara_script.rb:289:in `<main>'

**Comment by KrishnaKulkarni** [comment]
@mayaad @trinberg My suspicion is that there's a fairly unremarkable issue loading some of these pages, and that my script was previously ill-equipped to the handle the particular error triggered by the page-load-failure. I'll add error handling for this particular error raised `Capybara::Poltergeist::BrowserError` so that if this occurs again, the script will just log the error and keep chugging

**Comment by mayaad** [comment]
@KrishnaKulkarni this is looking great! pulled the diffs with no issues, and i've asked the analysts to report back with their thoughts. thank you!

**Comment by KrishnaKulkarni** [comment]
@mayaad Terrific. If they give the 👍 , go ahead click "Merge Pull Request" on the PR page:  https://github.com/edgi-govdata-archiving/versionista-outputter/pull/11
